version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NB_JOUEUR=nbJoueur
      - NB_PARTIE=nbPartie
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080