version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NB_JOUEUR=3
      - NB_PARTIE=3
    volumes:
      - .:/usr/src/app
    ports:
      - 7696:7696